CREATE TABLE `order_user_shopping_order` (
  `ordei_id` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '订单号',
  `material_id` int(64) unsigned NOT NULL DEFAULT '' COMMENT '食材ID',
  `status` int(10) unsigned NOT NULL DEFAULT '' COMMENT '订单状态 0表示无效 1表示未付款 2表示已发收货 3表示待收货 4表示已完成 5表示退款 6表示取消订单',
  `uid` int(64) unsigned NOT NULL DEFAULT '' COMMENT '用户ID',
  `shop_code` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '商店标识',
  `price` DOUBLE(12,4) NOT NULL DEFAULT '0' COMMENT '食材成交单价',
  `num` int(64) unsigned NOT NULL DEFAULT '' COMMENT '成交量',
  `discount_ammount` DOUBLE(12,4) NOT NULL DEFAULT '0' COMMENT '优惠价钱',
  `create_time` TIMESTAMP NOT NULL COMMENT '创建时间',
  `pay_time` TIMESTAMP COMMENT '付款时间',
  `send_time` TIMESTAMP COMMENT '发货时间',
  `finish_time` TIMESTAMP COMMENT '成交时间',
  `drawback_time` TIMESTAMP COMMENT '退款时间',
  `cancel_time` TIMESTAMP COMMENT '取消时间',
  `update_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最近更新时间',
  PRIMARY KEY (`ordei_id`,`material_id`),
  INDEX(`uid`),
  INDEX(`shop_code`),
  INDEX(`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单表'